# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qtDesigner/MatrixLed/uidesigner.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MiClassGui(object):
    #def __init__(self):
    #    gui = QtWidgets.QMainWindow()
    #    self.setupUi(gui)

    def setupUi(self, MiClassGui):
        MiClassGui.setObjectName("MiClassGui")
        MiClassGui.resize(514, 467)
        MiClassGui.setMinimumSize(QtCore.QSize(0, 0))
        self.centralWidget = QtWidgets.QWidget(MiClassGui)
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cmb_ports = QtWidgets.QComboBox(self.centralWidget)
        self.cmb_ports.setObjectName("cmb_ports")
        self.horizontalLayout_4.addWidget(self.cmb_ports)
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btn_config_port = QtWidgets.QPushButton(self.centralWidget)
        self.btn_config_port.setObjectName("btn_config_port")
        self.horizontalLayout_4.addWidget(self.btn_config_port)
        self.toolButton = QtWidgets.QToolButton(self.centralWidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.horizontalLayout_4.setStretch(0, 2)
        self.horizontalLayout_4.setStretch(2, 1)
        self.horizontalLayout_4.setStretch(3, 1)
        self.horizontalLayout_4.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_3.setContentsMargins(11, 11, 11, 10)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.txt_send = QtWidgets.QLineEdit(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_send.sizePolicy().hasHeightForWidth())
        self.txt_send.setSizePolicy(sizePolicy)
        self.txt_send.setMinimumSize(QtCore.QSize(100, 0))
        self.txt_send.setObjectName("txt_send")
        self.horizontalLayout_2.addWidget(self.txt_send)
        self.cmb_endline = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_endline.sizePolicy().hasHeightForWidth())
        self.cmb_endline.setSizePolicy(sizePolicy)
        self.cmb_endline.setMaximumSize(QtCore.QSize(50, 160000))
        self.cmb_endline.setObjectName("cmb_endline")
        self.horizontalLayout_2.addWidget(self.cmb_endline)
        self.btn_send = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send.sizePolicy().hasHeightForWidth())
        self.btn_send.setSizePolicy(sizePolicy)
        self.btn_send.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_2.addWidget(self.btn_send)
        self.btn_reset = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset.sizePolicy().hasHeightForWidth())
        self.btn_reset.setSizePolicy(sizePolicy)
        self.btn_reset.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_reset.setObjectName("btn_reset")
        self.horizontalLayout_2.addWidget(self.btn_reset)
        self.horizontalLayout_2.setStretch(0, 20)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 2)
        self.horizontalLayout_2.setStretch(3, 2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.textEdit_2 = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout.addWidget(self.textEdit_2)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 20)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.btn_stop = QtWidgets.QPushButton(self.centralWidget)
        self.btn_stop.setObjectName("btn_stop")
        self.horizontalLayout.addWidget(self.btn_stop)
        self.btn_start = QtWidgets.QPushButton(self.centralWidget)
        self.btn_start.setObjectName("btn_start")
        self.horizontalLayout.addWidget(self.btn_start)
        self.btn_quit = QtWidgets.QPushButton(self.centralWidget)
        self.btn_quit.setObjectName("btn_quit")
        self.horizontalLayout.addWidget(self.btn_quit)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MiClassGui.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MiClassGui)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 514, 19))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MiClassGui.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MiClassGui)
        self.mainToolBar.setObjectName("mainToolBar")
        MiClassGui.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MiClassGui)
        self.statusBar.setObjectName("statusBar")
        MiClassGui.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MiClassGui)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MiClassGui)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_Matrix_connection = QtWidgets.QAction(MiClassGui)
        self.actionAbout_Matrix_connection.setObjectName("actionAbout_Matrix_connection")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout_Matrix_connection)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MiClassGui)
        QtCore.QMetaObject.connectSlotsByName(MiClassGui)

    def retranslateUi(self, MiClassGui):
        _translate = QtCore.QCoreApplication.translate
        MiClassGui.setWindowTitle(_translate("MiClassGui", "Matrix connection"))
        self.label.setText(_translate("MiClassGui", "Available Ports"))
        self.btn_config_port.setText(_translate("MiClassGui", "Configure Port"))
        self.toolButton.setText(_translate("MiClassGui", "..."))
        self.groupBox.setTitle(_translate("MiClassGui", "Serial Connection editor"))
        self.btn_send.setText(_translate("MiClassGui", "Send"))
        self.btn_reset.setText(_translate("MiClassGui", "Reset"))
        self.btn_stop.setText(_translate("MiClassGui", "Stop serial"))
        self.btn_start.setText(_translate("MiClassGui", "Start serial"))
        self.btn_quit.setText(_translate("MiClassGui", "Quit"))
        self.menuFile.setTitle(_translate("MiClassGui", "File"))
        self.menuHelp.setTitle(_translate("MiClassGui", "Help"))
        self.actionOpen.setText(_translate("MiClassGui", "Open"))
        self.actionExit.setText(_translate("MiClassGui", "Exit"))
        self.actionAbout_Matrix_connection.setText(_translate("MiClassGui", "About Matrix connection"))

