# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uidesigner3.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MiClassGui(object):
    def setupUi(self, MiClassGui):
        MiClassGui.setObjectName("MiClassGui")
        MiClassGui.setWindowModality(QtCore.Qt.ApplicationModal)
        MiClassGui.resize(571, 520)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MiClassGui.sizePolicy().hasHeightForWidth())
        MiClassGui.setSizePolicy(sizePolicy)
        MiClassGui.setMinimumSize(QtCore.QSize(0, 0))
        MiClassGui.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        MiClassGui.setToolButtonStyle(QtCore.Qt.ToolButtonFollowStyle)
        MiClassGui.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralWidget = QtWidgets.QWidget(MiClassGui)
        self.centralWidget.setMinimumSize(QtCore.QSize(480, 360))
        self.centralWidget.setObjectName("centralWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_2.setSpacing(10)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.port_conf_layout = QtWidgets.QHBoxLayout()
        self.port_conf_layout.setContentsMargins(5, 1, 5, 1)
        self.port_conf_layout.setSpacing(6)
        self.port_conf_layout.setObjectName("port_conf_layout")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.port_conf_layout.addWidget(self.label)
        self.cmb_ports = QtWidgets.QComboBox(self.centralWidget)
        self.cmb_ports.setMinimumSize(QtCore.QSize(0, 29))
        self.cmb_ports.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cmb_ports.setObjectName("cmb_ports")
        self.port_conf_layout.addWidget(self.cmb_ports)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.port_conf_layout.addItem(spacerItem)
        self.btn_config_port = QtWidgets.QPushButton(self.centralWidget)
        self.btn_config_port.setMinimumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_config_port.setFont(font)
        self.btn_config_port.setObjectName("btn_config_port")
        self.port_conf_layout.addWidget(self.btn_config_port)
        self.port_conf_layout.setStretch(1, 1)
        self.port_conf_layout.setStretch(2, 2)
        self.port_conf_layout.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.port_conf_layout)
        self.serial_editor_layout = QtWidgets.QHBoxLayout()
        self.serial_editor_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.serial_editor_layout.setContentsMargins(11, 11, 11, 0)
        self.serial_editor_layout.setSpacing(1)
        self.serial_editor_layout.setObjectName("serial_editor_layout")
        self.serial_editor_group = QtWidgets.QGroupBox(self.centralWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.serial_editor_group.setFont(font)
        self.serial_editor_group.setObjectName("serial_editor_group")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.serial_editor_group)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout_2.setContentsMargins(0, 11, 0, 9)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.text_and_rw_layout = QtWidgets.QHBoxLayout()
        self.text_and_rw_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.text_and_rw_layout.setContentsMargins(1, 1, 1, 5)
        self.text_and_rw_layout.setSpacing(6)
        self.text_and_rw_layout.setObjectName("text_and_rw_layout")
        self.txt_send = QtWidgets.QLineEdit(self.serial_editor_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_send.sizePolicy().hasHeightForWidth())
        self.txt_send.setSizePolicy(sizePolicy)
        self.txt_send.setMinimumSize(QtCore.QSize(100, 27))
        self.txt_send.setObjectName("txt_send")
        self.text_and_rw_layout.addWidget(self.txt_send)
        self.cmb_endline = QtWidgets.QComboBox(self.serial_editor_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cmb_endline.sizePolicy().hasHeightForWidth())
        self.cmb_endline.setSizePolicy(sizePolicy)
        self.cmb_endline.setMinimumSize(QtCore.QSize(0, 27))
        self.cmb_endline.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cmb_endline.setObjectName("cmb_endline")
        self.text_and_rw_layout.addWidget(self.cmb_endline)
        self.btn_color = QtWidgets.QPushButton(self.serial_editor_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_color.sizePolicy().hasHeightForWidth())
        self.btn_color.setSizePolicy(sizePolicy)
        self.btn_color.setMinimumSize(QtCore.QSize(0, 29))
        self.btn_color.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btn_color.setObjectName("btn_color")
        self.text_and_rw_layout.addWidget(self.btn_color)
        self.btn_send = QtWidgets.QPushButton(self.serial_editor_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_send.sizePolicy().hasHeightForWidth())
        self.btn_send.setSizePolicy(sizePolicy)
        self.btn_send.setMinimumSize(QtCore.QSize(0, 29))
        self.btn_send.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_send.setFont(font)
        self.btn_send.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.btn_send.setObjectName("btn_send")
        self.text_and_rw_layout.addWidget(self.btn_send)
        self.btn_reset = QtWidgets.QPushButton(self.serial_editor_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_reset.sizePolicy().hasHeightForWidth())
        self.btn_reset.setSizePolicy(sizePolicy)
        self.btn_reset.setMinimumSize(QtCore.QSize(0, 29))
        self.btn_reset.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_reset.setFont(font)
        self.btn_reset.setObjectName("btn_reset")
        self.text_and_rw_layout.addWidget(self.btn_reset)
        self.text_and_rw_layout.setStretch(0, 20)
        self.text_and_rw_layout.setStretch(1, 2)
        self.text_and_rw_layout.setStretch(3, 2)
        self.text_and_rw_layout.setStretch(4, 2)
        self.verticalLayout.addLayout(self.text_and_rw_layout)
        self.txt_write = QtWidgets.QTextEdit(self.serial_editor_group)
        self.txt_write.setMinimumSize(QtCore.QSize(100, 27))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.txt_write.setFont(font)
        self.txt_write.setObjectName("txt_write")
        self.verticalLayout.addWidget(self.txt_write)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 15)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.serial_editor_layout.addWidget(self.serial_editor_group)
        self.verticalLayout_2.addLayout(self.serial_editor_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.start_stop_quit_layout = QtWidgets.QHBoxLayout()
        self.start_stop_quit_layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.start_stop_quit_layout.setContentsMargins(11, 11, 11, 0)
        self.start_stop_quit_layout.setSpacing(6)
        self.start_stop_quit_layout.setObjectName("start_stop_quit_layout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.start_stop_quit_layout.addItem(spacerItem2)
        self.btn_stop = QtWidgets.QPushButton(self.centralWidget)
        self.btn_stop.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_stop.setFont(font)
        self.btn_stop.setObjectName("btn_stop")
        self.start_stop_quit_layout.addWidget(self.btn_stop)
        self.btn_start = QtWidgets.QPushButton(self.centralWidget)
        self.btn_start.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_start.setFont(font)
        self.btn_start.setObjectName("btn_start")
        self.start_stop_quit_layout.addWidget(self.btn_start)
        self.btn_quit = QtWidgets.QPushButton(self.centralWidget)
        self.btn_quit.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_quit.setFont(font)
        self.btn_quit.setObjectName("btn_quit")
        self.start_stop_quit_layout.addWidget(self.btn_quit)
        self.start_stop_quit_layout.setStretch(0, 2)
        self.start_stop_quit_layout.setStretch(1, 1)
        self.start_stop_quit_layout.setStretch(2, 1)
        self.start_stop_quit_layout.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.start_stop_quit_layout)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 8)
        self.verticalLayout_2.setStretch(2, 2)
        self.verticalLayout_2.setStretch(3, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        MiClassGui.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MiClassGui)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 571, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        MiClassGui.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MiClassGui)
        self.mainToolBar.setObjectName("mainToolBar")
        MiClassGui.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MiClassGui)
        self.statusBar.setObjectName("statusBar")
        MiClassGui.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(MiClassGui)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MiClassGui)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_Matrix_connection = QtWidgets.QAction(MiClassGui)
        self.actionAbout_Matrix_connection.setObjectName("actionAbout_Matrix_connection")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionAbout_Matrix_connection)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MiClassGui)
        QtCore.QMetaObject.connectSlotsByName(MiClassGui)

    def retranslateUi(self, MiClassGui):
        _translate = QtCore.QCoreApplication.translate
        MiClassGui.setWindowTitle(_translate("MiClassGui", "Matrix connection"))
        self.label.setText(_translate("MiClassGui", "Available Ports:"))
        self.btn_config_port.setText(_translate("MiClassGui", "Configure Port"))
        self.serial_editor_group.setTitle(_translate("MiClassGui", "Serial Connection editor"))
        self.btn_color.setText(_translate("MiClassGui", "Color"))
        self.btn_send.setText(_translate("MiClassGui", "Send"))
        self.btn_reset.setText(_translate("MiClassGui", "Reset"))
        self.btn_stop.setText(_translate("MiClassGui", "Stop serial"))
        self.btn_start.setText(_translate("MiClassGui", "Start serial"))
        self.btn_quit.setText(_translate("MiClassGui", "Quit"))
        self.menuFile.setTitle(_translate("MiClassGui", "File"))
        self.menuHelp.setTitle(_translate("MiClassGui", "Help"))
        self.actionOpen.setText(_translate("MiClassGui", "Open"))
        self.actionExit.setText(_translate("MiClassGui", "Exit"))
        self.actionAbout_Matrix_connection.setText(_translate("MiClassGui", "About Matrix connection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MiClassGui = QtWidgets.QMainWindow()
    ui = Ui_MiClassGui()
    ui.setupUi(MiClassGui)
    MiClassGui.show()
    sys.exit(app.exec_())

